### PR TITLE
New features: token calculation logic and account information query logic.

### PR DESCRIPTION
**Pull request by aaronuu**
1. Tool for calculating token consumption quantity
2. API for querying account balance

### CODE REVIEW

**Comment by aaronuu** [comment]
@TheoKanning Request merge code

**Comment by fallbackwjj** [comment]
nice job

**Comment by TheoKanning** [comment]
Thanks!

**Comment by DevEmperor** [comment]
The API to request billing information doesn't seem to work. In Java it throws a 403 error and using the curl command, I get the following error message:

"Your request to GET /v1/dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret."

See #349

**Pull request merged**
