### PR TITLE
Enable user custom baseUrl of OpenAiService in the service package

### PR DESCRIPTION
**Pull request by SUTFutureCoder**
This change allows users to specify the baseurl to convert directly from the client package to the OpenAiService in the service package. In addition, because countries or regions such as China cannot use the original address of the OpenAI API, it is necessary to allow the baseurl to be specified.

### CODE REVIEW

**Comment by SUTFutureCoder** [comment]
solve api blocked issue of China by enable user custom baseUrl #145

**Comment by Kevin1118** [comment]
很需要

**Comment by heartdance** [comment]
请求审核合并

**Comment by ruofeilyu** [comment]
can we approve this? very needed for us to pass the baseurl since we can redirect to other host

**Comment by TheoKanning** [comment]
Closing this because it's already possible to set the base url via `Retrofit.newBuilder`.

I don't want to add any features just to circumvent OpenAIs deliberate country restrictions

**Pull request closed without merging**
