### PR TITLE
Support Assistants

### PR DESCRIPTION
**Pull request by remyohajinwa**
Provides Support for #390

### CODE REVIEW

**Comment by TheoKanning** [comment]
Thanks for adding this!

**Comment by vacuityv** [comment]
@remyohajinwa @TheoKanning  The tool object used to create "Assistants" need to be fixed. There is only one param "type" in this code. But when the tool type is "function" it need another param to defined the function. You can see the official api here: https://platform.openai.com/docs/api-reference/assistants/createAssistant
Maybe you guys can fix this.

**Comment by vacuityv** [comment]
image

this need to be fixed too

**Comment by remyohajinwa** [comment]
HI @vacuityv for the Tools....it's an Enum of Function, code_interepreter and retriever. you can check the class AssistantToolsEnum

**Comment by remyohajinwa** [comment]
@vacuityv taking a look at the second issue

**Comment by vacuityv** [comment]
@remyohajinwa  I know you defined the tool with an Enum of Function. I meant that when the type is function I need some param to pass the function.

**Comment by remyohajinwa** [comment]
Oh I see what you mean @vacuityv. Thank you for spotting this. will jump on it ASAP. but if you have a PR already. that would be nice

**Comment by remyohajinwa** [comment]
@vacuityv for AssistantRequest. I think it was a mistake with the naming convention. Taking a look. Will fix this.

`     AssistantBase build = AssistantRequest.builder()
                .model(TikTokensUtil.ModelEnum.GPT_4_1106_preview.getName())
                .name(MATH_TUTOR)
                .instructions(ASSISTANT_INSTRUCTION)
                .tools(Collections.singletonList(new Tool(AssistantToolsEnum.CODE_INTERPRETER)))
                .build();
                `

**Comment by vacuityv** [comment]
I just end my business work today and I haven’t fixed it. I can do it if you don’t have time for it.在 2023年11月13日，18:31，Remy Ohajinwa ***@***.***> 写道：﻿
Oh I see what you mean @vacuityv. Thank you for spotting this. will jump on it ASAP. but if you have a PR already. that would be nice

**Comment by vacuityv** [comment]
OK. Ths 在 2023年11月13日，18:41，彭伟 ***@***.***> 写道：﻿I just end my business work today and I haven’t fixed it. I can do it if you don’t have time for it.在 2023年11月13日，18:31，Remy Ohajinwa ***@***.***> 写道：﻿
Oh I see what you mean @vacuityv. Thank you for spotting this. will jump on it ASAP. but if you have a PR already. that would be nice

**Comment by remyohajinwa** [comment]
Taking a look

**Comment by remyohajinwa** [comment]
@vacuityv the Assistants is meant to work with Thread and Run. However the issue I worked on was to provide support for Assistant. It was expected that someone else would take up Thread or Run. An issue has to be created though.

**Comment by vacuityv** [comment]
@remyohajinwa I don't think this should be merged since it's just part of the feature. You guys should finish together and request together. It's real confused.

**Pull request merged**
