### PR TITLE
390 Added runs

### PR DESCRIPTION
**Pull request by bjorkman**
Added runs for assistants. Maybe the polling part should bve included in the service, but I left it open for now. I fe include it in the service (which would be nice) we should probably include a delay when polling and a timeout.

### CODE REVIEW

**Comment by bjorkman** [comment]
Removed code that didn't work in 1.8

**Comment by vacuityv** [comment]
@bjorkman  where is the method abount RunStep? You defined it but now use it, why ?

**Comment by vacuityv** [comment]
I will fix it

**Comment by vacuityv** [comment]
https://github.com/TheoKanning/openai-java/pull/408

**Pull request merged**
